Eloapp 13
kamilkuz/eloapp pull request #32
Opened 2019-01-24 20:59 UTC by kamilkuz

Tutaj głównie przenosiłem pliki więc pewnie nie musisz specjalnie zwracać uwagi na treść tych funkcji tylko bardziej co przyjmują, co zwracają i czy są w dobrych plikach

2019-01-24 21:01 UTC, kamilkuz commented on be/Service/UsersSvc.php
> +class UsersSvc
Ta klasa ma 3 metody publiczne które robią co innego i zastanawiam się czy tak naprawdę to jeszcze nie powinno być rozbite na 3 oddzielne klasy:
- UsersGetSvc
- UserAddSvc
- UserUpdateRatings

Czy jakieś takie. Co o tym sądzisz ?

2019-01-27 17:32 UTC, jazithedev requested changes

2019-01-27 17:32 UTC, jazithedev commented on be/Controller/RatingsHistoryCtrl.php
>  use \Psr\Http\Message\ServerRequestInterface as Request;
Ten `use` jest nieużywany. Prześledź jeszcze inne modyfikowane klasy, bo pozostawiłeś wiele takich nieużywanych klauzul :>.

2019-01-27 17:32 UTC, jazithedev commented on be/Controller/RatingsHistoryCtrl.php
> +        $responseArray = $this->ratingsHistorySvc->getRatingsHistory($code);
Tutaj zbyt wiele przeniosłeś do serwisu :). Do jego zadania może należeć właśnie m.in. wydobywanie historii gier danego gracza, ale już nie tworzenie obiektu, bądź tablicy odpowiedzi na request. Zawartość `$responseArray` powinieneś raczej już tworzyć w obrębie kontrolera w oparciu o dane wynikowe z `getRatingsHistory()`. To samo tyczy się wszystkich innych przeniesionych serwisów.

Pomyśl sobie chociażby tak. Co będzie, jak będziesz chciał użyć `getRatingsHistory()` w innym miejscu, ale nie będącym już kontrolerem? Byłaby lipa :P. Rozdzielamy właśnie ze wzgledu na reużywalność funkcjonalności.

2019-01-27 17:32 UTC, ktrzos commented on be/Service/UsersSvc.php
> +    public function getUsers(): array
W chwili obecnej mam pewne wątpliwości co do istnienia tej metody w tym miejscu i co do jej nazwy. Może tak w skrótach myślowych na razie będę pisać, bo nie wiem w sumie jeszcze jakie idealne rozwiązanie tu zastosować. Może ktoś z nas na coś wpadnie.

1. Nazwa `getUsers()` mówi o pobieraniu użytkowników, a tak naprawdę od samego w sobie pobierania jest repozytorium. Ta metoda zarazem i pobiera użytkowników, i przygotowuje ich dane odpowiednio do wysłania do FE.
2. Można użytkowników podawać jako parametr.
3. Klasa ma API: `getUsers`, `addUser`, `updateRatings`. Można zawsze tak patrzeć, czy metody do siebie pasują.
4. Część z metody `addUser()` można przenieść do innej klasy jako fabrykę, z której skorzystasz w kontrolerze i przesyłać już obiekt `User` do tej metody

2019-01-28 18:59 UTC, kamilkuz commented on be/Controller/RatingsHistoryCtrl.php
> +        $responseArray = $this->ratingsHistorySvc->getRatingsHistory($code);
@ktrzos 
Tak w sumie się zgadzam że ta metoda getRatingsHistory w ratingsHistorySvc robi sporo, ale włąśnie niewiem jak to sensownie podzielić. Ona obecnie robi mniej więcej 3 rzeczy:
1. Waliduje kod który przchodzi z FE i jeśli coś nie tak to zwraca warning (używa do tego userRepository)
2. Następnie pobiera dane za pomocą repozytorum: gameRepository (findSortedGamesForUser)
3. Przetwarza pobrane dane i formuje odpowidź (entitiesListToArray).

I teraz właśnie co gdzie powinno być. Bo jeśli punky 1 i 3 powinny być w kontrolerze to punkt 2 który będzie w servisie sprowadzi się tylko do wywołania metody z repo czyli do jeden linijki. No i jeszcze punkt 3 zawiera bardzo duży logiki i właśnie niewiem czy w kontrolerach powinna być logika ??

Kurde, szczerze to niewiem jak to powinno być żeby było czytelnie i poprawnie.

2019-01-28 19:03 UTC, kamilkuz commented on be/Service/UsersSvc.php
> +    public function getUsers(): array
@ktrzos 
1. Chyba podobny problem jak wyżej. Ona się składa tylko z dwóch podpunktów pobrania danych i przetwarzania. Ale też w tym przetwarzaniu jest baardzo dużo logiki no i pytanie czy taka logika powinna być w kontrolerze?
2. Nie bardzo rozumiem 
3. No właśnie niewiem? getUsers i addUser chyba tak, updateRatings chyba mniej, czyli updateRatings możnaby wydzielić do osobnej klasy??
4. Można ale wtedy metoda addUser w serwisie sprowadzi się tylko do spersisotowania i flusha, tak ?

2019-01-28 19:19 UTC, kamilkuz commented on be/Controller/RatingsHistoryCtrl.php
>  use \Psr\Http\Message\ServerRequestInterface as Request;
@ktrzos 
Ta, Ide mi tego w żaden sposób nie pokazywało. Teraz dopiero zainstalowałem sobie wtyczkę która podświetla nieużywane use, obejrzałem każdy plik i wywaliłem wszystko co mi podświetliło.
Kurde szczerze to vscode to reasona może jest dobre ale do phpa trochę ssie, każdą pierdołe to trzeba jakieś rozszerzenie...

2019-02-02 12:01 UTC, ktrzos commented on be/Controller/RatingsHistoryCtrl.php
> +        $responseArray = $this->ratingsHistorySvc->getRatingsHistory($code);
@kamilkuz 

Punkt 1. niekoniecznie można określić jako walidujący dane pochodzące FE. Tak naprawdę robiłby to niezależnie skąd te dane by się wzięły :). Pewne jest to, że walidacja musi być w ramach tego serwisu, ponieważ to serwis przyjmuje te dane i na nich operuje. Dobrze więc jest. Najpierw z repozytorium się pobiera:

```php
$user = $this->userRepository->findOneByCode($code);
```

a później ewentualnie można jakoś walidować

```php
$this->validateInputData($user);
```

or whatever :).

Punkt 2. to oczywistość, że musi tam być, bo to jednak główna logika tego serwisu :). Ale i ten 3. punkt bym do tego zaliczył. Zadaniem serwisu jest pobranie wszelkich danych historii danego gracza, i to właśnie jest przez ten serwis robione.

Jedynym elementem, jaki tu nie pasuje, to de facto ostatnia linijka metody `getRatingsHistory()`. Tutaj bardziej od razu zwracałbym wynik metody `entitiesListToArray()`.

2019-02-02 12:13 UTC, kamilkuz commented on be/Controller/RatingsHistoryCtrl.php
> +        $responseArray = $this->ratingsHistorySvc->getRatingsHistory($code);
@ktrzos 
Okej kumam. Tylko mam jedną wątpliwość. Bo jeśli metoda na końcu będzie zwracać to co zwraca entitiesListToArray to w takim razie co powinna zwracać walidacja na początku? stringa ? Czy może robić throw a w kontrolerze otaczać try-catchem ?

2019-02-02 12:20 UTC, kamilkuz commented on be/Controller/RatingsHistoryCtrl.php
> +        $responseArray = $this->ratingsHistorySvc->getRatingsHistory($code);
@ktrzos 
Chyba mam pomysł. Można zrobić funkcję walidującą która będzie zwracać stringa lub null (string to nie przeszło walidacju, null przeszło). I teraz użyć jej w serwisie i jeśli zwróci stringa to robić throw - dzięki temu mamy zabezpieczoną metodę w serwisie. Ale teraz trzeba by ją też wywołać w kontrolerze i jeśli zwróci stringa to zwracać responsa z warningiem i już nie wywoływać tej właściwej metody serwisu, co o tym myślisz ?

2019-02-02 12:29 UTC, jazithedev commented on be/Service/UsersSvc.php
> +    public function getUsers(): array
@kamilkuz 

Ad 1. Wiesz co, nie ma faktycznie sensu tego wrzucać do kontrolera. W sumie jak tak na trzeźwo na to patrzę, to nie jest źle.

Ad 2. Dziwny skrót myślowy miałem chyba :P. Do dotyczyło chyba metody `addUser()`. Zamiast przyjmować `array` można dawać obiekt `User` jako parametr, który zostanie wytworzony przez fabrykę wspomnianą w punkcie 4.

Ad 3. Hm, w sumie to możesz mieć rację :). Można tak zrobić.

Ad 4. W sumie, to chyba tak.

2019-02-02 17:44 UTC, kamilkuz commented on be/Controller/RatingsHistoryCtrl.php
> +        $responseArray = $this->ratingsHistorySvc->getRatingsHistory($code);
@ktrzos 
Zrobiłem według mojego pomysłu. Zernikja jak Ci się podoba, jak coś to mogę to wycofać :) Akurat w przypadku getRatingsHistory to teraz na samej górze w serwisie jest requireByCode co według mnie zabezpiecza serwis, bo się wywali jak przyjdzie zły kod.
Przerobiłem inne miejsca właśnie w sposób który opisałem czyli wydzieliłem funkcje do walidacji i użyłem w serwisie i kontrolerze tylko że serwis rzuca throwa a controler odpowiedź do FE. No i niestety ma to tą wadę że ta funkcja walidująca dwa razy się odpala i teoretycznie jest przez to nieoptymalnie - ale chyba to ma mniejsze znaczenie.

2019-02-04 19:27 UTC, jazithedev requested changes

2019-02-04 19:27 UTC, jazithedev commented on .gitignore
> +/nbproject
NetBeans :D? Paaanie, toć weź korzystaj z tego PhpStorma służbowego :D. NetBeans jest kiepskawy :/.

2019-02-04 19:27 UTC, jazithedev commented on be/Controller/RatingsHistoryCtrl.php
> +            return $response->withJson(['status' => 'warning', 'warningMsg' => $warningMsg]);
W takich momentach zawsze wolę, aby metody miały jeden raz użytą klauzulę `return` :). Kod
```
$response->withJson(['status' => 'warning', 'warningMsg' => $warningMsg])
```
można w sumie przenieść do jakiejś klasy nadrzędnej, bo chyba tego typu struktura występuje w wielu kontrolerach.

Ale ogólnie nie musisz zmieniać tutaj jak nie chcesz ;).

*EDIT:*
No i w sumie jak tak sobie po 10 minutach pomyślałem, to naprawdę można tutaj skorzystać z cebulowej architektury Slima :).

2019-02-04 19:27 UTC, jazithedev commented on be/Service/RatingsHistorySvc.php
> +    public function validateUserExist(string $code): ?string {
Dzielenie na jak najmniejsze metody - bardzo ładnie :).

2019-02-04 19:27 UTC, jazithedev commented on be/Service/RemoveGameSvc.php
> +            throw new InvalidArgumentException();
Tutaj wywali fatala. Musisz zmienić na `\InvalidArgumentException` i najlepiej dodać jakiś message w tych nawiasach. Dziwne, że IDE Ciebie o tym nie informuje :/.

W ogóle też tak rozkminiam, czy drugie użycie `validateRemoveLastGame()` czasem nie jest duplikacją kodu. Może po prostu z tego nie korzystać i założyć, że w tym miejscu `$code` jest już zwalidowany?

2019-02-04 19:27 UTC, jazithedev commented on be/Service/UsersSvc.php
> +            throw new InvalidArgumentException();
Podobnie jak we wcześniejszym komentarzu.

2019-02-04 19:27 UTC, jazithedev commented on be/Service/UsersSvc.php
> +    public function validateUpdateRatings(
Tak swoją drogą rozmyślam, czy by nie lepiej było, jeśli tego typu metody przeniosłoby się do osobnych klas. Jakichś `XxxValidator`. Nie wiem :P.

2019-02-04 19:54 UTC, kamilkuz commented on .gitignore
> +/nbproject
Oj bo vs code do phpa ssie, a ja chce koniecznie jakieś darmowe ide, żeby właśnie mieć jakąś alternatywe do płatnego storma. Stwierdziłem że do reasona będe korzystał z vs code a do phpa z netbeansa. Z tego co czytałem, z darmowych ide netbeans jest ponoć całkiem dobry, jak zacząłem korzystać to myśle że do moich zastosowań będzie wystarczający.
Ale fakt faktem że storm jest the best.

2019-02-04 19:56 UTC, kamilkuz commented on be/Controller/RatingsHistoryCtrl.php
> +            return $response->withJson(['status' => 'warning', 'warningMsg' => $warningMsg]);
No, właśnie też przeszło mi przez myśl że właśnie walidacje można do middlewearów wrzucić. Może trzeba będzie tak zrobić. Ale już w tym PRze mi się niechce :P

2019-02-04 19:57 UTC, kamilkuz commented on be/Service/UsersSvc.php
> +    public function validateUpdateRatings(
No, to się wiąże z wcześniejszym komentarzem że może to powinno być w middlewearach i wtedy to będzie musiała być osobna klasa. Ale to już tym PRrze bym tego nie ruszał :P

2019-02-04 20:04 UTC, ktrzos commented on be/Service/UsersSvc.php
> +    public function validateUpdateRatings(
Ok, masz rację.

2019-02-04 20:04 UTC, ktrzos commented on be/Controller/RatingsHistoryCtrl.php
> +            return $response->withJson(['status' => 'warning', 'warningMsg' => $warningMsg]);
Ok, w porządku. Zatem to będzie na inny PR :).

2019-02-04 20:05 UTC, jazithedev commented on .gitignore
> +/nbproject
Spoko ;). Ja z NB korzystałem z 5 lat :P przed PhpStormem.

2019-02-04 20:08 UTC, kamilkuz commented on be/Service/RemoveGameSvc.php
> +            throw new InvalidArgumentException();
No właśnie, tutaj do końca niewiem. Teoretecznie można to wywalić ale wtedy ryzyko stanowi jedynie to, że ktoś gdzieś indziej użyje tej metody i przekaże złe parametry (wtedy metoda by mogła zadziałać bez błędu ale zadziałała by źle co jest baaardzo niedobre). A tak teraz teoretycznie dzięki temu wywali mu się error i koleś zczai że przed użyciem musi zwalidować.
No ale właśnie to jest pewnie dyskusyjne, w leonie chyba tak nie robimy. Narazie bym zostawił.

Dodałem \ przed InvalidArgumentException. Messegy nie dodałem bo według mnie i tak żadnej cennej informacji tam nie przekaże. Najważniejsze według mnie jest to że to niepoprawny argument (o czym mówi nazwa klasy) oraz miejsce wystąpienie (o czym powie callstak przy wywaleniu).

2019-02-04 20:24 UTC, ktrzos commented on be/Service/RemoveGameSvc.php
> +            throw new InvalidArgumentException();
Co do braku messaga:
https://github.com/kalessil/phpinspectionsea/blob/master/docs/control-flow.md#general-exception-is-thrown
Ogólnie w PhpStorm jest warning i nie ma zielonej fajeczki :P.

Co do ryzyka. Możesz mieć rację. Też mi ciężko coś na ten temat z jakimś solidnym argumentem powiedzieć.
Co mi przychodzi na razie na myśl, to jak walidacja byłaby zrzucona do middleware, to w tym miejscu nie można byłoby jej klas używać.

2019-02-04 20:24 UTC, jazithedev approved these changes

2019-02-04 20:33 UTC, merged

2019-02-04 20:40 UTC, Qziem commented on be/Service/RemoveGameSvc.php
> +            throw new InvalidArgumentException();
Dodałem messegey