Eloapp 27
kamilkuz/eloapp pull request #34
Opened 2019-01-27 16:18 UTC by kamilkuz

2019-01-27 16:21 UTC, Qziem commented on fe/src/utils/DecoderWithWarnings.re
> +module MakeDecoderWithWarningsOrContent = (ContentDecoder: ContentDecoder) => {
Tutaj zrobiłem taki funktor który przekształca to co przyjdzie z BE w wariant: SUCCESS(content) | WARNING(msg).
Jest to funktor a nie zwykły moduł ponieważ typ content może być różny w zależności jaką odpowiedź przetwarzamy (np. gdy pobieramy ratingsHistory to content to list(ratingHistory)). O funktorach można poczytać tu:  https://reasonml.github.io/docs/en/module

2019-02-02 14:25 UTC, jazithedev requested changes

2019-02-02 14:25 UTC, jazithedev commented on be/Service/UsersSvc.php
> +    public function addUser(array $userArray): array
Na pewno zmiany odnoszące się tego pliku będzie trzeba zmienić (w związku z naszymi ostatnimi rozmowami w innych PR :)).

2019-02-02 14:25 UTC, jazithedev commented on fe/src/utils/DecoderWithWarnings.re
> +module MakeDecoderWithWarningsOrContent = (ContentDecoder: ContentDecoder) => {
@kamilkuz 

Ciekawa rzecz te funktory. To chyba trzeba wiedzieć gdzie ich używać. Po jakimś czasie pisania w tym pewnie dopiero wychodzi.

Pytanie. W tych nazwach funktora i modułów dobrze byłoby nawiązać co ten decode odznacza. Dekodować można mnóstwo rzeczy, a to chodzi o odpowiedź z backendu. Co o tym myślisz? Np. jakiś `RequestResponseDecoder`

2019-02-02 17:54 UTC, kamilkuz commented on be/Service/UsersSvc.php
> +    public function addUser(array $userArray): array
ta, jak już tamto domerguje to tu poprzerabiam

2019-02-04 21:39 UTC, kamilkuz commented on be/Service/UsersSvc.php
> +    public function addUser(array $userArray): array
@ktrzos 
Przerobiłem tutaj tak jak w tamtym PR-rze

2019-02-04 21:42 UTC, kamilkuz commented on fe/src/utils/DecoderWithWarnings.re
> +module MakeDecoderWithWarningsOrContent = (ContentDecoder: ContentDecoder) => {
@ktrzos 
No właśnie ja często mam problem z nazywaniem rzeczy :P
Zmieniłem nazwę pliku na ResponseDeckoder a metodę na MakeWithWarningsOrContent. I też zminiłem nazwy tych dekoderów w poszczególnych komponentach.

2019-02-05 17:55 UTC, jazithedev approved these changes

2019-02-05 18:33 UTC, merged